ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of SheSheng_onlyLQ_diffCoup'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_15 = ', GC_15
      WRITE(*,2) 'GC_16 = ', GC_16
      WRITE(*,2) 'GC_63 = ', GC_63
