C     Diagram 1
      DATA MAPCONFIG(1)/1/
      DATA TSTRATEGY(1)/2/
      DATA (IFOREST(I,-1,1),I=1,2)/5,4/
      DATA (SPROP(I,-1,1),I=1,4)/9000012,0,0,0/
      DATA TPRID(-1,1)/0/
      DATA (IFOREST(I,-2,1),I=1,2)/-1,3/
      DATA (SPROP(I,-2,1),I=1,4)/4,0,0,0/
      DATA TPRID(-2,1)/0/
C     Diagram 2
      DATA MAPCONFIG(2)/2/
      DATA TSTRATEGY(2)/2/
      DATA (IFOREST(I,-1,2),I=1,2)/1,5/
      DATA TPRID(-1,2)/4/
      DATA (SPROP(I,-1,2),I=1,4)/0,0,0,0/
      DATA (IFOREST(I,-2,2),I=1,2)/-1,4/
      DATA TPRID(-2,2)/9000012/
      DATA (SPROP(I,-2,2),I=1,4)/0,0,0,0/
      DATA (IFOREST(I,-3,2),I=1,2)/-2,3/
C     Diagram 3
      DATA MAPCONFIG(3)/3/
      DATA TSTRATEGY(3)/2/
      DATA (IFOREST(I,-1,3),I=1,2)/5,4/
      DATA (SPROP(I,-1,3),I=1,4)/9000012,0,0,0/
      DATA TPRID(-1,3)/0/
      DATA (IFOREST(I,-2,3),I=1,2)/1,-1/
      DATA TPRID(-2,3)/9000012/
      DATA (SPROP(I,-2,3),I=1,4)/0,0,0,0/
      DATA (IFOREST(I,-3,3),I=1,2)/-2,3/
C     Diagram 4
      DATA MAPCONFIG(4)/4/
      DATA TSTRATEGY(4)/2/
      DATA (IFOREST(I,-1,4),I=1,2)/5,4/
      DATA (SPROP(I,-1,4),I=1,4)/0,9000011,0,0/
      DATA TPRID(-1,4)/0/
      DATA (IFOREST(I,-2,4),I=1,2)/-1,3/
      DATA (SPROP(I,-2,4),I=1,4)/0,3,0,0/
      DATA TPRID(-2,4)/0/
C     Diagram 5
      DATA MAPCONFIG(5)/5/
      DATA TSTRATEGY(5)/2/
      DATA (IFOREST(I,-1,5),I=1,2)/1,5/
      DATA TPRID(-1,5)/3/
      DATA (SPROP(I,-1,5),I=1,4)/0,0,0,0/
      DATA (IFOREST(I,-2,5),I=1,2)/-1,4/
      DATA TPRID(-2,5)/9000011/
      DATA (SPROP(I,-2,5),I=1,4)/0,0,0,0/
      DATA (IFOREST(I,-3,5),I=1,2)/-2,3/
C     Diagram 6
      DATA MAPCONFIG(6)/6/
      DATA TSTRATEGY(6)/2/
      DATA (IFOREST(I,-1,6),I=1,2)/5,4/
      DATA (SPROP(I,-1,6),I=1,4)/0,9000011,0,0/
      DATA TPRID(-1,6)/0/
      DATA (IFOREST(I,-2,6),I=1,2)/1,-1/
      DATA TPRID(-2,6)/9000011/
      DATA (SPROP(I,-2,6),I=1,4)/0,0,0,0/
      DATA (IFOREST(I,-3,6),I=1,2)/-2,3/
C     Diagram 7
      DATA MAPCONFIG(7)/7/
      DATA TSTRATEGY(7)/2/
      DATA (IFOREST(I,-1,7),I=1,2)/1,5/
      DATA TPRID(-1,7)/4/
      DATA (SPROP(I,-1,7),I=1,4)/0,0,0,0/
      DATA (IFOREST(I,-2,7),I=1,2)/-1,3/
      DATA TPRID(-2,7)/9000012/
      DATA (SPROP(I,-2,7),I=1,4)/0,0,0,0/
      DATA (IFOREST(I,-3,7),I=1,2)/-2,4/
C     Diagram 8
      DATA MAPCONFIG(8)/8/
      DATA TSTRATEGY(8)/2/
      DATA (IFOREST(I,-1,8),I=1,2)/5,3/
      DATA (SPROP(I,-1,8),I=1,4)/0,0,-9000012,0/
      DATA TPRID(-1,8)/0/
      DATA (IFOREST(I,-2,8),I=1,2)/4,-1/
      DATA (SPROP(I,-2,8),I=1,4)/0,0,-4,0/
      DATA TPRID(-2,8)/0/
C     Diagram 9
      DATA MAPCONFIG(9)/9/
      DATA TSTRATEGY(9)/2/
      DATA (IFOREST(I,-1,9),I=1,2)/5,3/
      DATA (SPROP(I,-1,9),I=1,4)/0,0,-9000012,0/
      DATA TPRID(-1,9)/0/
      DATA (IFOREST(I,-2,9),I=1,2)/1,-1/
      DATA TPRID(-2,9)/9000012/
      DATA (SPROP(I,-2,9),I=1,4)/0,0,0,0/
      DATA (IFOREST(I,-3,9),I=1,2)/-2,4/
C     Diagram 10
      DATA MAPCONFIG(10)/10/
      DATA TSTRATEGY(10)/2/
      DATA (IFOREST(I,-1,10),I=1,2)/1,5/
      DATA TPRID(-1,10)/3/
      DATA (SPROP(I,-1,10),I=1,4)/0,0,0,0/
      DATA (IFOREST(I,-2,10),I=1,2)/-1,3/
      DATA TPRID(-2,10)/9000011/
      DATA (SPROP(I,-2,10),I=1,4)/0,0,0,0/
      DATA (IFOREST(I,-3,10),I=1,2)/-2,4/
C     Diagram 11
      DATA MAPCONFIG(11)/11/
      DATA TSTRATEGY(11)/2/
      DATA (IFOREST(I,-1,11),I=1,2)/5,3/
      DATA (SPROP(I,-1,11),I=1,4)/0,0,0,-9000011/
      DATA TPRID(-1,11)/0/
      DATA (IFOREST(I,-2,11),I=1,2)/4,-1/
      DATA (SPROP(I,-2,11),I=1,4)/0,0,0,-3/
      DATA TPRID(-2,11)/0/
C     Diagram 12
      DATA MAPCONFIG(12)/12/
      DATA TSTRATEGY(12)/2/
      DATA (IFOREST(I,-1,12),I=1,2)/5,3/
      DATA (SPROP(I,-1,12),I=1,4)/0,0,0,-9000011/
      DATA TPRID(-1,12)/0/
      DATA (IFOREST(I,-2,12),I=1,2)/1,-1/
      DATA TPRID(-2,12)/9000011/
      DATA (SPROP(I,-2,12),I=1,4)/0,0,0,0/
      DATA (IFOREST(I,-3,12),I=1,2)/-2,4/
C     Number of configs
      DATA MAPCONFIG(0)/12/
