ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' External Params'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'mdl_cabi = ', MDL_CABI
      WRITE(*,*) 'aEWM1 = ', AEWM1
      WRITE(*,*) 'mdl_Gf = ', MDL_GF
      WRITE(*,*) 'aS = ', AS
      WRITE(*,*) 'mdl_ymt = ', MDL_YMT
      WRITE(*,*) 'mdl_ymtau = ', MDL_YMTAU
      WRITE(*,*) 'mdl_lc = ', MDL_LC
      WRITE(*,*) 'mdl_mpi = ', MDL_MPI
      WRITE(*,*) 'mdl_FPi53 = ', MDL_FPI53
      WRITE(*,*) 'mdl_FPi13 = ', MDL_FPI13
      WRITE(*,*) 'mdl_FPid23 = ', MDL_FPID23
      WRITE(*,*) 'mdl_FPiu23 = ', MDL_FPIU23
      WRITE(*,*) 'mdl_cabi2 = ', MDL_CABI2
      WRITE(*,*) 'mdl_MZ = ', MDL_MZ
      WRITE(*,*) 'mdl_MM = ', MDL_MM
      WRITE(*,*) 'mdl_MTA = ', MDL_MTA
      WRITE(*,*) 'mdl_MT = ', MDL_MT
      WRITE(*,*) 'mdl_MH = ', MDL_MH
      WRITE(*,*) 'mdl_WZ = ', MDL_WZ
      WRITE(*,*) 'mdl_WW = ', MDL_WW
      WRITE(*,*) 'mdl_WT = ', MDL_WT
      WRITE(*,*) 'mdl_WH = ', MDL_WH
      WRITE(*,*) 'mdl_WPi53uno = ', MDL_WPI53UNO
      WRITE(*,*) 'mdl_WPi13uno = ', MDL_WPI13UNO
      WRITE(*,*) 'mdl_WPiu23uno = ', MDL_WPIU23UNO
      WRITE(*,*) 'mdl_WPid23uno = ', MDL_WPID23UNO
      WRITE(*,*) 'mdl_WPi53due = ', MDL_WPI53DUE
      WRITE(*,*) 'mdl_WPi13due = ', MDL_WPI13DUE
      WRITE(*,*) 'mdl_WPiu23due = ', MDL_WPIU23DUE
      WRITE(*,*) 'mdl_WPid23due = ', MDL_WPID23DUE
      WRITE(*,*) 'mdl_WPi53tre = ', MDL_WPI53TRE
      WRITE(*,*) 'mdl_WPi13tre = ', MDL_WPI13TRE
      WRITE(*,*) 'mdl_WPiu23tre = ', MDL_WPIU23TRE
      WRITE(*,*) 'mdl_WPid23tre = ', MDL_WPID23TRE
      WRITE(*,*)  ' Internal Params'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'mdl_cos__cabi = ', MDL_COS__CABI
      WRITE(*,*) 'mdl_CKM1x1 = ', MDL_CKM1X1
      WRITE(*,*) 'mdl_sin__cabi = ', MDL_SIN__CABI
      WRITE(*,*) 'mdl_CKM1x2 = ', MDL_CKM1X2
      WRITE(*,*) 'mdl_CKM2x1 = ', MDL_CKM2X1
      WRITE(*,*) 'mdl_CKM2x2 = ', MDL_CKM2X2
      WRITE(*,*) 'mdl_MassB = ', MDL_MASSB
      WRITE(*,*) 'mdl_ONE1x1 = ', MDL_ONE1X1
      WRITE(*,*) 'mdl_ONE1x2 = ', MDL_ONE1X2
      WRITE(*,*) 'mdl_ONE1x3 = ', MDL_ONE1X3
      WRITE(*,*) 'mdl_ONE2x1 = ', MDL_ONE2X1
      WRITE(*,*) 'mdl_ONE2x2 = ', MDL_ONE2X2
      WRITE(*,*) 'mdl_ONE2x3 = ', MDL_ONE2X3
      WRITE(*,*) 'mdl_ONE3x1 = ', MDL_ONE3X1
      WRITE(*,*) 'mdl_ONE3x2 = ', MDL_ONE3X2
      WRITE(*,*) 'mdl_ONE3x3 = ', MDL_ONE3X3
      WRITE(*,*) 'mdl_FPi13__exp__2 = ', MDL_FPI13__EXP__2
      WRITE(*,*) 'mdl_lc__exp__2 = ', MDL_LC__EXP__2
      WRITE(*,*) 'mdl_Ypi13 = ', MDL_YPI13
      WRITE(*,*) 'mdl_FPi53__exp__2 = ', MDL_FPI53__EXP__2
      WRITE(*,*) 'mdl_Ypi53 = ', MDL_YPI53
      WRITE(*,*) 'mdl_FPid23__exp__2 = ', MDL_FPID23__EXP__2
      WRITE(*,*) 'mdl_Ypid23 = ', MDL_YPID23
      WRITE(*,*) 'mdl_FPiu23__exp__2 = ', MDL_FPIU23__EXP__2
      WRITE(*,*) 'mdl_Ypiu23 = ', MDL_YPIU23
      WRITE(*,*) 'mdl_MZ__exp__2 = ', MDL_MZ__EXP__2
      WRITE(*,*) 'mdl_MZ__exp__4 = ', MDL_MZ__EXP__4
      WRITE(*,*) 'mdl_sqrt__2 = ', MDL_SQRT__2
      WRITE(*,*) 'mdl_MH__exp__2 = ', MDL_MH__EXP__2
      WRITE(*,*) 'mdl_complexi = ', MDL_COMPLEXI
      WRITE(*,*) 'mdl_conjg__CKM1x1 = ', MDL_CONJG__CKM1X1
      WRITE(*,*) 'mdl_conjg__CKM1x2 = ', MDL_CONJG__CKM1X2
      WRITE(*,*) 'mdl_conjg__CKM2x1 = ', MDL_CONJG__CKM2X1
      WRITE(*,*) 'mdl_conjg__CKM2x2 = ', MDL_CONJG__CKM2X2
      WRITE(*,*) 'mdl_aEW = ', MDL_AEW
      WRITE(*,*) 'mdl_MW = ', MDL_MW
      WRITE(*,*) 'mdl_sqrt__aEW = ', MDL_SQRT__AEW
      WRITE(*,*) 'mdl_ee = ', MDL_EE
      WRITE(*,*) 'mdl_MW__exp__2 = ', MDL_MW__EXP__2
      WRITE(*,*) 'mdl_sw2 = ', MDL_SW2
      WRITE(*,*) 'mdl_cw = ', MDL_CW
      WRITE(*,*) 'mdl_sqrt__sw2 = ', MDL_SQRT__SW2
      WRITE(*,*) 'mdl_sw = ', MDL_SW
      WRITE(*,*) 'mdl_g1 = ', MDL_G1
      WRITE(*,*) 'mdl_gw = ', MDL_GW
      WRITE(*,*) 'mdl_vev = ', MDL_VEV
      WRITE(*,*) 'mdl_vev__exp__2 = ', MDL_VEV__EXP__2
      WRITE(*,*) 'mdl_lam = ', MDL_LAM
      WRITE(*,*) 'mdl_yt = ', MDL_YT
      WRITE(*,*) 'mdl_ytau = ', MDL_YTAU
      WRITE(*,*) 'mdl_muH = ', MDL_MUH
      WRITE(*,*) 'mdl_ee__exp__2 = ', MDL_EE__EXP__2
      WRITE(*,*) 'mdl_sw__exp__2 = ', MDL_SW__EXP__2
      WRITE(*,*) 'mdl_cw__exp__2 = ', MDL_CW__EXP__2
      WRITE(*,*)  ' Internal Params evaluated point by point'
      WRITE(*,*)  ' ----------------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'mdl_sqrt__aS = ', MDL_SQRT__AS
      WRITE(*,*) 'mdl_G__exp__2 = ', MDL_G__EXP__2
